### ISSUE TITLE
Windows 7でインストールしようとするとエラーが出る

### ISSUE THREAD

**Issue by YSRKEN** [kazatsuyu/fafnir#12]
# 概要・再現手順
Visual Studio 2017＋Windows 7 SP1(64bit)といった環境でインストールしようとすると、次のようなエラー表示が出てしまう。LLVMのパスやツールセット名などは全てデフォルトとした。

![image](https://user-images.githubusercontent.com/3734392/37083886-41a82f38-2234-11e8-8309-ee4211448d40.png)

**Comment by kazatsuyu** [comment]
NoNewline オプションが使えるのは PowerShell V5 以降のようなので、NoNewlineを使わずにできる方法に変更する
