### ISSUE TITLE
Translate README into English / READMEの英語化

### ISSUE THREAD

**Issue by kazatsuyu** [kazatsuyu/fafnir#13]
とりあえず書いてみたものの絶対破綻しているので英語に強い人がいたら助けて下さい。  
I tried to write README.md in English, but it's probably broken. Please help me.

# Fafnir

Clang MSBuild toolset for Visual Studio 2017

## Abstract

This is a MSBuild toolset with LLVM Clang for Windows.

## Requirement

* Visual Studio 2017
* Clang For Windows
  [Download](http://releases.llvm.org/download.html) from LLVM website and install it, or use the [snapshot](http://llvm.org/builds/). You can also use one of your build.

## Usage

First, Download the [ratest release](https://github.com/kazatsuyu/fafnir/releases/).
Its host architecture must be same to Clang for Windows.

### Install

Run install.bat, and set LLVM path and toolset name.  
Administrator authority is required for installaion.  
To use with CMake, the toolset name must matches `v[0-9]+_clang_.*`.  

### How to use with Visual Studio IDE

Open a project property, select \[Configuration Properties -> General\] in the left list,
select \[Platform toolset\] in \[General\] groupe, and select the toolset name that you named during installation (default name is v100_clang_fafnir).
Then you can build using LLVM clang.

### How to use with CMake

When you run cmake command, set `-G` option `"Visual Studio 15 2017"` or `"Visual Studio 15 2017 Win64"`, and set `-T` iotion the name that you named during installation.

## How to build Fafnir

The toolset that installed by Fafnir is required to build Fafnir.  
Also, LLVM must be support C++17. (The releases are build by [LLVM Snapshot Build](http://llvm.org/builds/))  
CMake is also required.

* Build 64bit version
```
cmake -G "Visual Studio 15 2017 Win64" -T <installed Fafnir toolset> -DCMAKE_INSTALL_PREFIX=<path to install>
cmake --build . --config Release --target INSTALL
```

* Build 32bit version
```
cmake -G "Visual Studio 15 2017" -T <installed Fafnir toolset> -DCMAKE_INSTALL_PREFIX=<path to install>
cmake --build . --config Release --target INSTALL
```

Run above command, you get deployed files in path to install.

**Comment by akinomyoga** [comment]
お呼びじゃないかもしれないけれどそんな気がしたので失礼させていただきます (先日 Twitter で脅すよようなことを書いてしまってすみません)。全然問題ない文章です。文法的には色々あるかもしれないけれど、違う意味の単語を間違って使っているとかがないので、意味が取れます。全然気になりません

<details><summary>以下気づいた範囲・分かる範囲で機械的な修正</summary>

> Abstract

/* 不要と思う。論文なんかだと abstract だけれど、説明書で abstract という見出しは見ない気がする。
   あえて書くなら "What is Fafnir?" または "What is this?" のような形式を見かける */

> Requirement

Requirements

> from LLVM website

from the LLVM website

> one of your build.

one of your builds.

> Clang For Windows

Clang for Windows /* 前置詞は普通 capitalize しない */

> First, Download the ratest release.

First, download the latest release.

> Its host architecture must be same to Clang for Windows.

Its host architecture must be the same to Clang for Windows.

/* same [形容詞] よりは the same [代名詞] の方が普通 */

> Install

How to install /* 他の見出しとの統一。英語では結構気にする */

> set LLVM path and toolset name.

set the LLVM path and a toolset name.

> installaion.

installation.

> must matches

must match

> Open a project property

Open the project property

> the toolset name that you named during installation 

the toolset name that you set during the installation /* 馬から落馬 */

> [General] groupe

[General] group

> default name is

the default name is

> you can build using LLVM clang.

you can build the project using LLVM clang. /* この意味のときは build は他動詞 */

> set -G option "Visual Studio 15 2017" or "Visual Studio 15 2017 Win64"

specify "Visual Studio 15 2017" or "Visual Studio 15 2017 Win64" to the option -G

> set -T iotion the name that you named during installation.

specify the toolset name, that you set during the installation, to the option -T

> The toolset that installed by Fafnir

The toolset installed by Fafnir

> Also, LLVM must be support C++17 (The releases are build by LLVM Snapshot Build)

Also, LLVM that supports C++17 must be used (e.g. the release binaries of Fafnir are built by LLVM Snapshot Build).

/* LLVM must support C++17 だと LLVM project 本家に対する要求と取れる。
   文と括弧を並べるときは、括弧は文の中 (つまり . より前)。 */

> Run above command, you get deployed files in path to install.

Run the above commands, and then you will find deployed files in the install path.

/* 単数形→複数形、接続詞抜け、冠詞 */

----

全般: 日本語では文と文の間や区切りの良いところで改行を入れる文化があるが、英語圏ではそのような文化はない (文と文を空白で繋げて "段落" とし、(テキスト形式では) 段落と段落を空行 (二重改行) で繋げて文章とする) ので、却って読みにくい。そのまま行内で繋げて書く。
</details>

**Comment by kazatsuyu** [comment]
ありがとうございます！　指摘された箇所を書き直してREADMEを更新しました
