### ISSUE TITLE
Q: How to uninstall the toolsets?

### ISSUE THREAD

**Issue by mloskot** [kazatsuyu/fafnir#14]
First, thanks for the very useful MSBuild add-in. I've used it with VS2017 and it works very well.

I have installed choosing names `v100_clang_fafnir` and `fafnir_clang_cl`.

Is there any way to uninstall the toolsets?

**Comment by akinomyoga** [comment]
Currently fafnir's uninstaller is not yet provided (#11), but you can manually uninstall toolsets (cf https://github.com/kazatsuyu/fafnir/issues/9#issuecomment-370248026) by removing the following directories:

```
$(VSInstallDir)\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\$(YourToolsetName)
$(VSInstallDir)\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets\$(YourToolsetName)
```

Here `$(VSInstallDir)` is typically `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`, and `$(YourToolsetName)` is `v100_clang_fafnir` or `fafnir_clang_cl` in your case. Fafnir doesn't change other settings, so just removing the directories completely removes the toolset.

**Comment by mloskot** [comment]
@akinomyoga Thanks a lot! I think it would be helpful to have this instruction in the README, see #15
