### ISSUE TITLE
ビルドがキャッシュされない

### ISSUE THREAD

**Issue by yumetodo** [kazatsuyu/fafnir#5]
一度ビルドしていても再びビルドする際に0からやり直している

**Comment by kazatsuyu** [comment]
cmake --build を実行するとキャッシュされないがVisual Studioを立ち上げてビルドを実行するとキャッシュされているように見えるので何が違っているのか調査する

**Comment by yumetodo** [comment]
>Visual Studioを立ち上げてビルドを実行すると

そんなこともない。

再現手順

1. 既存のコンソールアプリケーションのプロジェクトを開く
2. ビルド→構成マネージャー→(現在のプロジェクトの)構成→新規作成→名前を`clang_Release`、設定コピー元に空、新しいソリューション構成を作成するにチェックを付けてOK
3. プロジェクト→プロパティ→Platform Toolsetで追加したToolset名を選択、適用
4. `Ctrl`+`F5`でコンパイル&実行
5. `Ctrl`+`F5`でコンパイル&実行、コンパイルが走る

**Comment by kazatsuyu** [comment]
うーん、Visual Studio IDEはMSBuildを起動するよりも前にリビルド判定しているように見える。私の環境では再現できない……。

https://docs.microsoft.com/ja-jp/visualstudio/msbuild/file-tracking  
コマンドラインから起動した場合、MSBuildはおそらくこれを利用してファイル書き込みをトラッキングしている。これは予想だが、子プロセスの書き込みはトラッキングできるようだが、孫プロセスの書き込みはトラッキングできていないのではないだろうか。  
ビルド時に Microsoft.Build.CPPTasks.ClangCompile.write.1.tlog というファイルが作られていて、その中身にオブジェクトファイルのパスが入っていないと、ビルドに成功していないと判断されるように思われる。

**Comment by yumetodo** [comment]
https://www.axfc.net/u/3891024.7z
pass: fafnir
これが実際に検証に使ってたProjectなんですが、これでも再現できないですかね？

**Comment by kazatsuyu** [comment]
試してみようとしたら斧が落ちているのでまた今度にする

とりあえず、書き込みがトラッキングされないのは孫プロセスだからではないことが判明した。
どうやらCreateFileにフックを仕込むことで出力を監視しているようだが、ファイルの移動が行われた場合、それを検知できていない。
clangは一時ファイルに出力してからリネームしているので、MoveFile関数の呼び出しにフックを仕込んで、リネームの直後に対象を一瞬開く処理を追加することでトラッキングログに出力されると推測できる。
その方針でDLLインジェクションを実装することにする。

**Comment by kazatsuyu** [comment]
40bd4d8f204573df862cd4f73e4da19966c95c7c
DLLインジェクション実装した

**Comment by yumetodo** [comment]
やっぱりキャッシュされていない

**Comment by kazatsuyu** [comment]
Configuration名がclang_Debugになっているのが原因でvcpkgがビルド依存関係のファイルを出力できていなかった。DeubgもしくはReleaseから始まる名前にしないといけないようだが、vcpkgの問題なのでこちらで修正を入れる必要はないと判断しようと思う
