### ISSUE TITLE
clang.exe (LLVM公式 64 bit) がクラッシュする (Win 10 Home / VS 2017)

### ISSUE THREAD

**Issue by akinomyoga** [kazatsuyu/fafnir#9]
Release x86 でコンパイルできません。clang.exe がクラッシュするようです。~~Debug x86 / Debug x64 / Release x64 では何れもコンパイル・実行できます~~ (**訂正**: 何れの設定でも同様にクラッシュするようです)。もしかすると、こちらの設定の問題の可能性もありますが、ご報告します。

**状況**

- 環境は Windows 10 Home / Visual Studio 2017 Community
- <a href="http://releases.llvm.org/download.html">LLVM Download Page</a> から Clang for Windows ~~(32-bit)~~ (**訂正**: すみません、これはコピペミスです。入れたのは 64 bit でした) をダウンロードして実行・既定の場所にインストールした。
- fafnir-v1.0.1.0-win64.zip をダウンロードして install.bat を実行し、パス `C:\Program Files\LLVM` を指定して後は既定の設定でインストールした。
- Visual Studio の IDE を立ち上げてコンソールアプリケーション (ConsoleApplication1) のプロジェクトを作成した。プロジェクトのプロパティを開いて、プラットフォームツールセットを `v100_clang_fafnir` にした。
- Release x86 で緑の▶のボタンからビルド・実行をした。UTF-16 (LE) は対応していないというメッセージが出たので、ファイルの文字コードを全部 UTF-8 (BOM つき) にして、改めて実行したところ、`clang.exe` がクラッシュする。~~Release x64 / Debug x64 / Debug x86 では無事にコンパイルされ実行される~~

以下 `出力` 画面の内容です。

```
1>------ ビルド開始: プロジェクト: ConsoleApplication1, 構成: Release Win32 ------
1>stdafx.cpp
1>stdafx.h
1>Wrote crash dump file "C:\Users\murase\AppData\Local\Temp\clang.exe-bd458e.dmp"
1>0x00007FF78472AD15 (0x0000000000000001 0x00007FF700000000 0x000001F9126C2E80 0x000001F91263D2C0)
1>0x00007FF78474337A (0x0000006A9578D8B0 0x000001F9126C2E80 0x0000000000000000 0x00007FF78461636B)
1>0x00007FF784740541 (0x000001F9126C2E70 0x0000000000000000 0x000001F9126BF460 0x0000000000000001)
1>0x00007FF78470C719 (0x0000006A9578D950 0x0000000000000000 0x000001F9126C2E70 0x0000000000000000)
1>0x00007FF784097CCC (0x0000000000000000 0x00007FFA15260A58 0x0000000000000040 0x0000000000000030)
1>0x00007FF7846129C2 (0x0000000000000000 0x0000000000000000 0x0000000000000050 0x000001F91261E9C0)
1>0x00007FF78407FDDA (0x00007FFA14F96D90 0x00007FF700000002 0x000001F900000002 0x00007FF700000002)
1>0x00007FF78404B460 (0x0000006A9578DC38 0x00007FF78404601B 0x000001F91263A1F0 0x0000000000000038)
1>0x00007FF7840C027C (0x000000000000007E 0x00000000000003F0 0x000000C0FFFFFEED 0x000001F91262A880)
1>0x00007FF7829A5E6B (0x0000000000000074 0x0000000000000000 0x0000000000000000 0x0000000000000000)
1>0x00007FF7829A4293 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
1>0x00007FF785322D81 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
1>0x00007FFA15F01FE4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
1>0x00007FFA189EEFC1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
1>clang.exe : error : clang frontend command failed due to signal (use -v to see invocation)
1>clang version 5.0.1 (tags/RELEASE_501/final)
1>Target: i686-pc-windows-msvc
1>Thread model: posix
1>InstalledDir: C:\Program Files\LLVM\bin
1>clang.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
1>clang.exe: note: diagnostic msg:
1>********************
1>
1>PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
1>Preprocessed source(s) and associated run script(s) are located at:
1>clang.exe: note: diagnostic msg: C:\Users\murase\AppData\Local\Temp\stdafx-daef12.hh
1>clang.exe: note: diagnostic msg: C:\Users\murase\AppData\Local\Temp\stdafx-daef12.sh
1>clang.exe: note: diagnostic msg:
1>
1>********************
1>プロジェクト "ConsoleApplication1.vcxproj" のビルドが終了しました -- 失敗。
========== ビルド: 0 正常終了、1 失敗、0 更新不要、0 スキップ ==========

```

**Comment by akinomyoga** [comment]
すみません。LLVM のページからコピペするのを間違えました。入れたのは 64 bit です。

> 異なるアーキテクチャのものをインストールした時にクラッシュが発生するのは良くないので、インストール時点やDLLインジェクションを実行する前にチェックを行ってエラーを出すようにしようと思います。

これには賛成です!

**Comment by kazatsuyu** [comment]
あ、64-bitでしたか。確かによく見たらクラッシュダンプが64bit...
了解しました。調査します

**Comment by kazatsuyu** [comment]
ちなみに、 https://github.com/kazatsuyu/fafnir/releases/tag/v1.0.0.2 を使った場合どうなるか試していただくことは可能でしょうか。このバージョンだとキャッシュされないとかインストール時にツールセット名を変えれないなどの問題がありますが、DLLインジェクションを行っていないのでDLLインジェクションが問題を引き起こしているかどうかが分かるので……

**Comment by akinomyoga** [comment]
後出しですみません。`stdafx.h` に `#include <iostream>` を書くと問題が再現するようです。`ConsoleApplication1.cpp` に直接 `#include <iostream>` を書いた時は問題は起こりませんでした。ConsoleApplication1 は実は昔試しにプロジェクトだけ作ってみたというものだったので記述が不正確になってしまいました。ConsoleApplication2 を作ってみて気づきました。

LLVM 64 bit を再インストールしてみましたが、これは変化はありませんでした。

> 了解しました。調査します

お手数をおかけします。よろしくお願いいたします

**Comment by akinomyoga** [comment]
> ちなみに、 https://github.com/kazatsuyu/fafnir/releases/tag/v1.0.0.2 を使った場合
ありがとうございます。試してみます。

**Comment by kazatsuyu** [comment]
> stdafx.h に #include <iostream> を書くと問題が再現するようです。

こちらでも再現しました。ありがとうございます

**Comment by kazatsuyu** [comment]
[LLVMの最新のSnapshot Build](http://llvm.org/builds/)を利用すると発生しないですね。おそらくLLVM側の実装に問題があってiostreamのパース中にICEが発生しているのではないかと思います。
古い（と言っても安定版のはずではありますが……）LLVMでコンパイルできない問題に関してはどうしようもないので、仕様とするしかないような気がします

**Comment by kazatsuyu** [comment]
コマンドラインから直接clangを実行しても同じようにクラッシュしたので、LLVMのバグと判断します。

**Comment by akinomyoga** [comment]
ありがとうございました

- LLVM の snapshot を入れてみたところ、動くことが確認できました。
- 古い LLVM 5.0.1 でも "プリコンパイル済みヘッダを使用しない" にすればコンパイルできるようです。ドキュメントにこの workaround について書いても良いかもしれないと思いました
- 教えていただいた v1.0.0.2 はインストールしようとしたのですが、何だかよく分からないことになりました…。ツールセットに別名をつけて入れようとした所、ツールセット名が空文字列になってしまうようです…が、これは v1.0.1.0 で直っているようですね。

**Comment by akinomyoga** [comment]
ところで…試行錯誤している内に雑多な名前のツールセットがたくさんできてしまったのですが、これらを削除する方法は提供されていますか

**Comment by kazatsuyu** [comment]
今のところはないです。すみません。ツールセットのフォルダで完結しているので、
```
$(VSInstallDir)\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets
$(VSInstallDir)\Common7\IDE\VC\VCTargets\Platforms\x64\PlatformToolsets
```
ディレクトリの下からそれぞれ該当する名前のフォルダを削除してください。  
そのうちアンインストール手段も追加します

**Comment by akinomyoga** [comment]
ありがとうございます!

**Comment by kazatsuyu** [comment]
LLVM 6.0.0で発生しなくなったようなので、とりあえず今後同じ症状に悩まされる人は減ると思われる。documentに特筆するほどではなさそう。
